name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        publishToNuget:
          description: 'Publish to nuget'
          required: true
          default: true
          type: boolean

jobs:
  dotnet:
    uses: mathieumack/MyGithubActions/.github/workflows/dotnetlib.yml@main
    with:
      publishToNuget: false
    secrets:
      NUGETPACKAGEIDENTIFIER: ${{ secrets.NUGETPACKAGEIDENTIFIER }}
      NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}